### ISSUE TITLE
导入m3u8download失败

### ISSUE THREAD

**Issue by Jerry080801** [hecoter/hm3u8dl_cli#13]
Traceback (most recent call last):
  File "/Users/jerry2/Downloads/m3u8download.py", line 1, in <module>
    import hm3u8dl_cli
  File "/opt/homebrew/lib/python3.9/site-packages/hm3u8dl_cli/__init__.py", line 5, in <module>
    from hm3u8dl_cli.m3u8Parser import Parser, download_infos
  File "/opt/homebrew/lib/python3.9/site-packages/hm3u8dl_cli/m3u8Parser/Parser.py", line 4, in <module>
    import requests, m3u8
  File "/Users/jerry2/Downloads/m3u8.py", line 1, in <module>
    from hm3u8dl_cli import m3u8download
ImportError: cannot import name 'm3u8download' from partially initialized module 'hm3u8dl_cli' (most likely due to a circular import) (/opt/homebrew/lib/python3.9/site-packages/hm3u8dl_cli/__init__.py)
[Finished in 145ms with exit code 1]
[cmd: ['python3', '-u', '/Users/jerry2/Downloads/m3u8download.py']]
[dir: /Users/jerry2/Downloads]
[path: /Library/Frameworks/Python.framework/Versions/2.7/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/jerry2/Downloads/VMware Fusion Tech Preview.app/Contents/Public:~/.dotnet/tools:/Library/Apple/usr/bin:/usr/local/mysql/bin]

**Comment by hecoter** [comment]
在pycharm使用出现的问题吗？我的是正常的，未知问题
